import Navbar from "@/components/Navbar";
import { GHOUL_DNA, BANANA_DNA } from "@/lib/character";
import { Cpu, Palette, Shirt, User, Zap } from "lucide-react";

export default function CharacterPage() {
  const characters = [
    { dna: GHOUL_DNA, icon: <Cpu size={24} />, color: "bg-black" },
    { dna: BANANA_DNA, icon: <Zap size={24} />, color: "bg-yellow-400" }
  ];

  return (
    <main className="min-h-screen bg-[var(--bg-main)] pb-24">
      <Navbar />
      
      <header className="max-w-7xl mx-auto px-6 pt-20 pb-16 border-b border-[var(--border-soft)] text-center">
        <h1 className="text-5xl md:text-7xl typography-title uppercase tracking-tighter mb-6">Character Protocols</h1>
        <p className="text-xl text-[var(--text-secondary)] max-w-2xl mx-auto leading-relaxed">
          The digital souls of Pager. These are the DNA protocols used by our AI to generate consistent brand assets and character illustrations.
        </p>
      </header>

      {characters.map(({ dna, icon, color }, idx) => (
        <div key={dna.name} className={`py-20 ${idx % 2 === 1 ? 'bg-gray-50' : ''}`}>
          <div className="max-w-7xl mx-auto px-6">
            <div className="flex items-center gap-4 mb-12">
              <div className={`w-12 h-12 ${color} rounded-full flex items-center justify-center text-white`}>
                {icon}
              </div>
              <h2 className="text-4xl md:text-5xl typography-title uppercase tracking-tighter">{dna.name}</h2>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-12 mb-12">
              {/* Physical Attributes */}
              <section className="space-y-6">
                <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-gray-400">
                  <User size={14} /> <span>Physical DNA</span>
                </div>
                <div className="space-y-4">
                  {Object.entries(dna.physical_attributes).map(([key, value]) => (
                    <div key={key} className="border-l-2 border-black pl-4">
                      <span className="block text-[10px] uppercase font-bold text-gray-400">{(key as string).replace('_', ' ')}</span>
                      <span className="text-lg font-medium">{value as string}</span>
                    </div>
                  ))}
                </div>
              </section>

              {/* Outfit & Gear */}
              <section className="space-y-6">
                <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-gray-400">
                  <Shirt size={14} /> <span>Outfit & Gear</span>
                </div>
                <div className="space-y-4">
                  {Object.entries(dna.outfit).map(([key, value]) => (
                    <div key={key} className="border-l-2 border-black pl-4">
                      <span className="block text-[10px] uppercase font-bold text-gray-400">{key}</span>
                      <span className="text-lg font-medium">{value as string}</span>
                    </div>
                  ))}
                </div>
              </section>

              {/* Art Style */}
              <section className="space-y-6">
                <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-gray-400">
                  <Palette size={14} /> <span>Art Protocol</span>
                </div>
                <div className="space-y-4">
                  <div className="border-l-2 border-black pl-4">
                    <span className="block text-[10px] uppercase font-bold text-gray-400">Base Style</span>
                    <span className="text-lg font-medium">{dna.art_style.base}</span>
                  </div>
                  <div className="border-l-2 border-black pl-4">
                    <span className="block text-[10px] uppercase font-bold text-gray-400">Lighting</span>
                    <span className="text-lg font-medium">{dna.art_style.lighting}</span>
                  </div>
                  <div className="flex flex-wrap gap-2 pt-2">
                    {dna.art_style.keywords.map(kw => (
                      <span key={kw} className="px-2 py-1 bg-white text-[10px] font-bold uppercase rounded-sm border border-[var(--border-soft)]">
                        {kw}
                      </span>
                    ))}
                  </div>
                </div>
              </section>
            </div>

            <div className="bg-black text-white p-8 md:p-12 rounded-sm">
              <h3 className="text-2xl font-bold mb-4 uppercase tracking-tighter">AI Integration: {dna.name}</h3>
              <p className="text-gray-400 mb-8 max-w-xl">
                This data ensures that {dna.name} remains consistent across all story banners generated by our protocol.
              </p>
              <code className="block bg-white/10 p-4 text-xs font-mono text-gray-200 overflow-x-auto">
                {`"Illustration featuring ${dna.name}: ${dna.physical_attributes.species} with ${dna.physical_attributes.skin_color} skin..."`}
              </code>
            </div>
          </div>
        </div>
      ))}
    </main>
  );
}
